[package]
name = "phone-book-management-cli-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
comfy-table = "7.1.3"
csv = "1.3.1"
diesel = { version = "2.2.6", features = ["sqlite"] }
diesel_migrations = "2.2.0"
dotenv = "0.15.0"

